# Generated by Django 6.0.3 on 2026-04-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_accidentreport_image_accidentreport_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='severity',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], max_length=20),
        ),
    ]
