# Generated by Django 6.0.6 on 2026-06-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_accidentreportphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='incident_type',
            field=models.CharField(choices=[('dangerous_situation', 'Situation dangereuse'), ('near_miss', 'Presque accident'), ('accident', 'Accident'), ('fatal_accident', 'Accident mortel')], default='dangerous_situation', max_length=50),
        ),
    ]
