# Generated by Django 6.0.6 on 2026-06-25 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_accidentreport_incident_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom du chantier')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chantier',
                'verbose_name_plural': 'Chantiers',
            },
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='worksite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.worksite', verbose_name='Chantier associé'),
        ),
    ]
