# Generated by Django 6.0.6 on 2026-07-10 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_remove_inspection_photo_inspectionphoto'),
        ('reports', '0006_worksite_accidentreport_worksite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='days_lost',
            field=models.IntegerField(default=0, verbose_name="Jours d'arrêt"),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'action")),
                ('description', models.TextField(verbose_name="Description de l'action")),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('done', 'Clôturé'), ('canceled', 'Annulé')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accident_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='reports.accidentreport')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_actions', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='controls.inspection')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_actions', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
            ],
            options={
                'verbose_name': 'Action de sécurité',
                'verbose_name_plural': "Plan d'actions",
                'ordering': ['-created_at'],
            },
        ),
    ]
