# Generated by Django 6.0.6 on 2026-07-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_accidentreport_days_lost_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé logiquement'),
        ),
    ]
