# Generated by Django 5.1.15 on 2026-08-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_accidentreport_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='incident_type',
            field=models.CharField(choices=[('dangerous_situation', 'Situation dangereuse'), ('near_miss', 'Presque accident'), ('accident', 'Accident'), ('fatal_accident', 'Accident mortel'), ('terrain_other', 'Terrain (Autres)')], default='dangerous_situation', max_length=50),
        ),
    ]
