# Generated by Django 5.1.15 on 2026-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_accidentreport_incident_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Clôturé'),
        ),
        migrations.AddField(
            model_name='action',
            name='completion_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='action_proofs/', verbose_name='Preuve de complétion (visuelle)'),
        ),
        migrations.AddField(
            model_name='action',
            name='completion_proof_text',
            field=models.TextField(blank=True, null=True, verbose_name='Preuve de complétion (texte)'),
        ),
        migrations.AddField(
            model_name='action',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('pending_validation', 'En attente de validation'), ('done', 'Clôturé'), ('canceled', 'Annulé')], default='todo', max_length=20),
        ),
    ]
