# Generated by Django 5.2.11 on 2026-02-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.AddField(
            model_name='slide',
            name='file',
            field=models.FileField(null=True, upload_to='slides/'),
        ),
    ]
