# Generated by Django 5.2.11 on 2026-02-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0002_remove_slide_image_slide_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
