# Generated by Django 5.2.11 on 2026-02-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0003_quiz_passing_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
