# Generated by Django 6.0.6 on 2026-06-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0005_slideshow_invited_users_slideshow_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
