# Generated by Django 6.0.6 on 2026-07-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0006_slideshow_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='signature',
            field=models.TextField(blank=True, help_text='Signature manuscrite Base64', null=True),
        ),
    ]
