# Generated by Django 5.1.15 on 2026-08-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0007_quizsubmission_signature'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together=set(),
        ),
    ]
