# Generated by Django 5.1.15 on 2026-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0008_alter_quizsubmission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='signed_quizzes/', verbose_name='PDF Signé'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivée'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Terminée'),
        ),
    ]
