# Generated by Django 6.0.3 on 2026-03-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
