# Generated by Django 5.1.15 on 2026-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_remove_inspection_photo_inspectionphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentitem',
            name='category',
            field=models.CharField(choices=[('EQUIPEMENT', 'Équipement'), ('VEHICULE', 'Véhicule')], max_length=20),
        ),
    ]
