# Generated by Django 6.0.3 on 2026-03-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
