# Generated by Django 6.0.6 on 2026-06-09 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blockedmacaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedmacaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_mac_addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
