# Generated by Django 6.0.6 on 2026-07-10 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_blockedmacaddress_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('sst', 'Sauveteur Secouriste du Travail (SST)'), ('caces', 'CACES (Engins de chantier)'), ('elec', 'Habilitation Électrique'), ('hauteur', 'Travail en Hauteur'), ('medical', 'Visite Médicale Périodique'), ('other', 'Autre Certification')], max_length=20)),
                ('custom_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Intitulé précis')),
                ('obtained_date', models.DateField(verbose_name="Date d'obtention")),
                ('expiration_date', models.DateField(verbose_name="Date d'expiration")),
                ('certificate', models.FileField(blank=True, null=True, upload_to='habilitations/', verbose_name='Justificatif PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habilitation',
                'verbose_name_plural': 'Habilitations',
                'ordering': ['expiration_date'],
            },
        ),
    ]
