# Generated by Django 5.1.15 on 2026-08-19 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_habilitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name="Nom de l'agence")),
                ('region', models.CharField(max_length=255, verbose_name='Région')),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='min_slideshows_per_year',
            field=models.IntegerField(default=10, verbose_name='Nombre minimum de causeries par an'),
        ),
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.agency', verbose_name='Agence'),
        ),
    ]
