# Generated by Django 5.1.15 on 2026-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_agency_user_min_slideshows_per_year_user_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=50, unique=True, verbose_name='Nom de la vue')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('allow_admin', models.BooleanField(default=True, verbose_name='Autoriser Admin')),
                ('allow_technician', models.BooleanField(default=True, verbose_name='Autoriser Technicien')),
                ('allow_agency', models.BooleanField(default=True, verbose_name='Autoriser Agence')),
            ],
            options={
                'verbose_name': 'Permission de Vue',
                'verbose_name_plural': 'Permissions de Vues',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='min_reports_per_year',
            field=models.IntegerField(default=5, verbose_name='Nombre minimum de remontées par an'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('technician', 'Technicien'), ('agency', 'Agence')], default='technician', max_length=20, verbose_name='Rôle'),
        ),
    ]
