# Generated by Django 6.0.2 on 2026-03-16 14:06

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalfile',
            name='file',
            field=models.FileField(upload_to='personal_files/', validators=[files.models.validate_file_size]),
        ),
    ]
