# Generated by Django 6.0.6 on 2026-07-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_personalfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom du produit')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Fabricant')),
                ('sds_file', models.FileField(upload_to='sds/', verbose_name='Fiche de Données de Sécurité (FDS)')),
                ('pictograms', models.CharField(blank=True, help_text='Pictogrammes séparés par des virgules, ex: GHS02,GHS07', max_length=255, verbose_name='Pictogrammes de danger')),
                ('description', models.TextField(blank=True, verbose_name='Usage et remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produit chimique',
                'verbose_name_plural': 'Produits chimiques / FDS',
            },
        ),
    ]
