# Generated by Django 5.1.15 on 2026-08-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_chemicalproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('electricity', 'Électricité'), ('water', 'Eaux'), ('harness', 'Harnais'), ('other', 'Autre')], default='electricity', max_length=50, verbose_name='Type de visite')),
                ('custom_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type de visite personnalisé')),
                ('date', models.DateField(verbose_name='Date de la visite')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Prochaine échéance')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires / Observations')),
                ('inspector', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisme / Inspecteur')),
                ('document', models.FileField(blank=True, null=True, upload_to='periodic_visits/', verbose_name='Rapport PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visite périodique',
                'verbose_name_plural': 'Visites périodiques',
                'ordering': ['-date'],
            },
        ),
    ]
